// AUDIT.md serializer for the firm-audit probe (Phase 6 D-09 hybrid format).
//
// Pure function: AuditReport in, markdown string out. Caller writes the
// result via a single writeFile() call (Pitfall 6 — never appendFile per row).
//
// D-10 enforcement: remediationToTargetPhase + statusLabel use TS `never`
// exhaustiveness. Adding a new Status or Remediation value without updating
// these switches fails `pnpm typecheck` — the writer cannot ship a row with
// an unknown enum value.
//
// Output structure:
//   1. Title + intro paragraph
//   2. Summary table (grep-friendly): | Firm | Tier | Status | Items | Remediation | Target Phase |
//   3. Per-firm evidence sections (## <id> (tier, status))
//   4. Run metadata block (timestamps, counts, probe version)

import type {
  AuditReport,
  AuditRow,
  Remediation,
  Status,
} from './types.js';

/**
 * Map a Remediation value to its canonical target phase string.
 * Adding a new Remediation value without a case here fails `tsc --noEmit`.
 */
export function remediationToTargetPhase(r: Remediation): string {
  switch (r) {
    case 'enable-js-render-detail': return 'Phase 7';
    case 'fix-selector':            return 'Phase 7';
    case 'disable-firm':            return 'immediate';
    case 'migrate-to-sitemap':      return 'Phase 9';
    case 'monitor':                 return 'Phase 10/11';
    default: {
      const _exhaustive: never = r;
      throw new Error(`Unhandled remediation: ${_exhaustive as string}`);
    }
  }
}

/**
 * Short human-readable label for a Status value (used in summary table cell).
 * Same `never` enforcement: new Status values fail typecheck without a case.
 */
function statusLabel(s: Status): string {
  switch (s) {
    case 'OK':                       return 'OK';
    case 'list-fail':                return 'list-fail';
    case 'selector-empty':           return 'selector-empty';
    case 'detail-identical':         return 'detail-identical';
    case 'detail-empty':             return 'detail-empty';
    case 'detail-quality-unknown':   return 'detail-quality-unknown';
    default: {
      const _exhaustive: never = s;
      throw new Error(`Unhandled status: ${_exhaustive as string}`);
    }
  }
}

function summaryRowLine(row: AuditRow): string {
  const firmCell = row.disabled
    ? `${row.firmId} (disabled, baseline)`
    : row.firmId;
  const remediationCell = row.remediation ?? 'n/a';
  const targetCell = row.targetPhase ?? 'n/a';
  return `| ${firmCell} | ${row.tier} | ${statusLabel(row.status)} | ${row.items} | ${remediationCell} | ${targetCell} |`;
}

function evidenceSection(row: AuditRow): string {
  const disabledTag = row.disabled ? ' (disabled, baseline)' : '';
  return [
    `## ${row.firmId} (${row.tier}, ${statusLabel(row.status)})${disabledTag}`,
    '',
    `- **Name:** ${row.firmName}`,
    `- **Items:** ${row.items}`,
    `- **Evidence:** ${row.evidence}`,
    `- **Remediation:** ${row.remediation ?? 'n/a'}`,
    `- **Target Phase:** ${row.targetPhase ?? 'n/a'}`,
  ].join('\n');
}

function metadataBlock(report: AuditReport): string {
  const m = report.runMetadata;
  return [
    '## Run metadata',
    '',
    `- **Started:** ${m.startedAt}`,
    `- **Finished:** ${m.finishedAt}`,
    `- **Include disabled:** ${m.includeDisabled}`,
    `- **Total firms:** ${m.totalFirms}`,
    `- **OK:** ${m.okCount}`,
    `- **Non-OK:** ${m.nonOkCount}`,
    `- **Probe version:** ${m.probeVersion ?? 'unknown'}`,
    `- **Output path:** ${report.outputPath}`,
  ].join('\n');
}

/**
 * Serialize an AuditReport to a markdown string per Phase 6 D-09 hybrid format.
 * Caller MUST write the entire returned string in ONE writeFile call (Pitfall 6).
 */
export function renderAuditMarkdown(report: AuditReport): string {
  const header = [
    '# Firm Audit Report',
    '',
    `_Generated by_ \`pnpm audit:firms\` _at_ ${report.runMetadata.finishedAt}`,
    '',
    'See `.planning/phases/06-firm-audit-probe/06-CONTEXT.md` for status & remediation vocabulary.',
    '',
  ].join('\n');

  const summaryTable = [
    '## Summary',
    '',
    '| Firm | Tier | Status | Items | Remediation | Target Phase |',
    '|------|------|--------|-------|-------------|--------------|',
    ...report.rows.map(summaryRowLine),
    '',
  ].join('\n');

  const evidenceBlocks = [
    '## Per-firm evidence',
    '',
    ...report.rows.map((r) => evidenceSection(r) + '\n'),
  ].join('\n');

  return [header, summaryTable, evidenceBlocks, metadataBlock(report), ''].join('\n');
}
